# Updated: Force fresh deployment - ensure all changes are reflected
[build]
  publish = "client/dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to handle backend calls during development
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://replit.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self'; object-src 'none'; child-src 'none'; worker-src 'self'; manifest-src 'self';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# Functions for serverless backend with Firebase
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for API endpoints to functions
[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/firebase"
  to = "/.netlify/functions/auth-firebase"
  status = 200

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/contractors/*"
  to = "/.netlify/functions/contractors"
  status = 200

[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/bids/*"
  to = "/.netlify/functions/bids"
  status = 200

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "client/dist"
  autoLaunch = false 